# Generated by Django 5.2.13 on 2026-07-01 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordereditems',
            old_name='products',
            new_name='product',
        ),
    ]
