# Generated by Django 5.2.13 on 2026-07-01 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_products_ordereditems_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordereditems',
            old_name='product',
            new_name='products',
        ),
    ]
