# Generated by Django 5.2.13 on 2026-07-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_product_ordereditems_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='total_price',
            field=models.FloatField(default=0),
        ),
    ]
